name: Docker test

on:
  push:
    branches:
      - 'main'
    tags:
      - '*'
  pull_request:

jobs:
  docker-test:
    env:
      COMPOSE_ARGS: -f docker-compose.yml -f docker-compose.ci.yml
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.5

      - name: docker-compose up
        run: docker-compose ${{ env.COMPOSE_ARGS }} up -d

      - name: Wait for some things to be inserted
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 50
          retry_wait_seconds: 2
          warning_on_retry: false
          command: if (($(docker-compose ${{ env.COMPOSE_ARGS }} logs wdqs-updater | grep "org.wikidata.query.rdf.tool.Updater - Polled" | wc -l) >= 10)); then exit 0; else exit 1; fi
      - name: Make a sparql request
        run: |
          NUM_BINDINGS=$(curl 'http://localhost:9999/bigdata/namespace/wdq/sparql' -H 'Accept: application/sparql-results+json' --data-raw 'query=SELECT+*+WHERE%7B+%3Fs+%3Fp+%3Fo+%7D' | jq '.results.bindings | length')
          # should be plenty more than 10
          if [[ "$NUM_BINDINGS" -lt 10 ]]; then
              exit 1
          fi
      - name: docker-compose logs > output.log
        if: always()
        run: docker-compose ${{ env.COMPOSE_ARGS }} logs --no-color > "output.log"

      - name: Archive output.log
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: DockerTestLog
          if-no-files-found: error
          path: output.log

